### ISSUE TITLE
Banner Support

### ISSUE THREAD

**Issue by TheMeinerLP** [OneLiteFeatherNET/Microtus#17]
This issue tracks support for Banner Support and Shield Support

Status 29.06.2023:
![image](https://github.com/OneLiteFeatherNET/Microtus/assets/6745190/42fd54ae-0900-492b-806c-c546a0b0afce)

Status: 30.06.2023:
![image](https://github.com/OneLiteFeatherNET/Microtus/assets/6745190/3f0c9186-22f2-4401-b55d-3309d9f00ff9)

**Comment by TheMeinerLP** [comment]
Fixes: https://github.com/Minestom/Minestom/discussions/1664
Fixes: https://github.com/Minestom/Minestom/issues/977

**Comment by theEvilReaper** [comment]
The following snippets demonstrate how to create a banner and a sign which has patterns

Banner:
```java
ItemStack banner = ItemStack.builder(Material.GREEN_BANNER)
    .meta(BannerMeta.class, builder -> {
         builder.patterns(List.of(new BannerMeta.Pattern(DyeColor.BLACK, BannerPattern.MOJANG)));
         builder.patterns(List.of(BannerMeta.from(DyeColor.BLACK, BannerPattern.MOJANG)));
    })
    .build();
```

Shield:
```java
var stack = ItemStack.builder(Material.SHIELD)
      .meta(ShieldMeta.class, builder -> {
           builder.patterns(List.of(new BannerMeta.Pattern(DyeColor.LIME, BannerPattern.CREEPER)));
           builder.baseColor(DyeColor.BLACK);
      })
      .build();
```

The code displays the current state. It is possible that it may change with respect with focus on the method calls
