### ISSUE TITLE
add PlayerChangeGameModeEvent

### ISSUE THREAD

**Issue by Sombian** [OneLiteFeatherNET/Microtus#43]
^^

**Comment by TheMeinerLP** [comment]
Can be closed 
Ref: -> https://github.com/OneLiteFeatherNET/Microtus/blob/master/minestom-patches/0002-Add-player-gamemode-change-event.patch
Also here -> https://www.javadoc.io/doc/net.onelitefeather.microtus/Minestom/latest/net/minestom/server/event/player/PlayerGameModeChangeEvent.html
<img width="787" alt="image" src="https://github.com/OneLiteFeatherNET/Microtus/assets/6745190/9fb0470d-8d67-4c02-a31c-02bda8288f31">

**Comment by Sombian** [comment]
didnt knew! my apologies.
