### ISSUE TITLE
[Feature]: Replace limits in packets with properties

### ISSUE THREAD

**Issue by TheMeinerLP** [OneLiteFeatherNET/Microtus#83]
### Is your feature request related to a problem?

The hardcoded limits in packets like `ServerLinksPacket` (e.g., `MAX_ENTRIES = 100`) make the system less flexible.

### Describe the solution you'd like

Replace the hardcoded limits with configurable properties to allow more flexibility and adaptability.

### Describe alternatives you've considered

Alternative solutions include setting higher limits or making the limits configurable via environment variables or configuration files.

**Comment by joelramilison** [comment]
It seems that when you wrote 'configurable properties' you weren't referring to configuration files. What do you mean by properties, technically?

**Comment by TheMeinerLP** [comment]
There is a class called: `ServerFlag` that carries all configuration properties that get read out via `-Dpropert.name=value`
