### ISSUE TITLE
[Feature]: add Microtus Logo on Readme

### ISSUE THREAD

**Issue by OneLiteFeather** [OneLiteFeatherNET/Microtus#91]
### Is your feature request related to a problem?

There is no microtus logo at the side, which isn't that great.

### Describe the solution you'd like

It would look better if there is the microtus logo. The project would improve the re-recognition value. In addition there is already the logo in the wiki

**Comment by OneLiteFeather** [comment]
Here is the logo in the wiki readme
https://github.com/OneLiteFeatherNET/wiki/blob/master/README.md

**Comment by Abhishek022001** [comment]
can i work on this issue?

**Comment by TheMeinerLP** [comment]
Yeah go on!

**Comment by Abhishek022001** [comment]
Thank you!

**Comment by TheMeinerLP** [comment]
Resolve in #92
